"use client";

import { useMemo, useState } from "react";

const MONTHS = ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"];
const DAYS = ["Pzt", "Sal", "Çar", "Per", "Cum", "Cmt", "Paz"];

const CATEGORIES = [
  { value: "egitim", label: "Eğitim", icon: "🎓", color: "#60a5fa", bg: "linear-gradient(145deg, rgba(37,99,235,.42), rgba(14,165,233,.16))" },
  { value: "is", label: "İş", icon: "💼", color: "#a78bfa", bg: "linear-gradient(145deg, rgba(124,58,237,.42), rgba(168,85,247,.16))" },
  { value: "gunluk", label: "Günlük", icon: "✅", color: "#34d399", bg: "linear-gradient(145deg, rgba(5,150,105,.38), rgba(16,185,129,.16))" },
  { value: "saglik", label: "Sağlık", icon: "💪", color: "#fb7185", bg: "linear-gradient(145deg, rgba(225,29,72,.38), rgba(251,113,133,.16))" },
  { value: "finans", label: "Finans", icon: "💰", color: "#fbbf24", bg: "linear-gradient(145deg, rgba(217,119,6,.38), rgba(251,191,36,.16))" },
  { value: "kisisel", label: "Kişisel", icon: "✨", color: "#22d3ee", bg: "linear-gradient(145deg, rgba(8,145,178,.38), rgba(34,211,238,.16))" },
  { value: "not", label: "Gün Notu", icon: "📝", color: "#f472b6", bg: "linear-gradient(145deg, rgba(190,24,93,.38), rgba(244,114,182,.16))" },
];
const PRIORITIES = [{ value: "dusuk", label: "Düşük", icon: "🟢" }, { value: "orta", label: "Orta", icon: "🟡" }, { value: "yuksek", label: "Yüksek", icon: "🔴" }];
const STATUSES = [{ value: "pending", label: "Bekliyor", icon: "⬜", color: "#cbd5e1" }, { value: "done", label: "Tamamlandı", icon: "✅", color: "#22c55e" }, { value: "failed", label: "Tamamlanamadı", icon: "❌", color: "#ef4444" }];
const GOAL_COLORS = [{ value: "blue", label: "Mavi", color: "#60a5fa" }, { value: "purple", label: "Mor", color: "#a78bfa" }, { value: "green", label: "Yeşil", color: "#34d399" }, { value: "yellow", label: "Sarı", color: "#fbbf24" }, { value: "pink", label: "Pembe", color: "#f472b6" }, { value: "cyan", label: "Camgöbeği", color: "#22d3ee" }];
const MONTH_GRADIENTS = ["#1d4ed844", "#7c3aed44", "#05966944", "#d9770644", "#e11d4844", "#0891b244", "#65a30d44", "#ea580c44", "#4f46e544", "#db277744", "#0f766e44", "#64748b44"];

const glass = { border: "1px solid rgba(255,255,255,.14)", boxShadow: "0 22px 55px rgba(0,0,0,.34), inset 0 1px 0 rgba(255,255,255,.10)", backdropFilter: "blur(14px)" };
const inputStyle = { width: "100%", border: "1px solid rgba(255,255,255,.22)", background: "rgba(2,6,23,.58)", color: "#f8fafc", borderRadius: "14px", padding: "11px 12px", outline: "none" };
const compactButton = { border: "1px solid rgba(255,255,255,.22)", background: "rgba(15,23,42,.66)", color: "#f8fafc", borderRadius: "9px", padding: "6px 8px", cursor: "pointer", fontWeight: 800, fontSize: "11px", lineHeight: 1 };

function pad(v) { return String(v).padStart(2, "0"); }
function localISO(d) { return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`; }
function todayISO() { return localISO(new Date()); }
function dateFromISO(v) { const [y, m, d] = String(v || todayISO()).split("-").map(Number); return new Date(y || new Date().getFullYear(), (m || 1) - 1, d || 1, 12); }
function addDays(d, n) { const x = new Date(d); x.setDate(x.getDate() + n); return x; }
function startOfWeek(d) { const x = new Date(d); const day = x.getDay() || 7; x.setDate(x.getDate() - day + 1); x.setHours(12, 0, 0, 0); return x; }
function weekNumber(d) { const t = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate())); const day = t.getUTCDay() || 7; t.setUTCDate(t.getUTCDate() + 4 - day); const s = new Date(Date.UTC(t.getUTCFullYear(), 0, 1)); return Math.ceil(((t - s) / 86400000 + 1) / 7); }
function buildWeeks(year) { const first = new Date(Number(year), 0, 1, 12); const last = new Date(Number(year), 11, 31, 12); let cur = startOfWeek(first); const weeks = []; while (cur <= last) { const days = Array.from({ length: 7 }, (_, i) => addDays(cur, i)); const visible = days.find((d) => d.getFullYear() === Number(year)) || days[0]; weeks.push({ id: `${year}-${localISO(cur)}`, number: weekNumber(cur), monthIndex: visible.getMonth(), monthName: MONTHS[visible.getMonth()], days }); cur = addDays(cur, 7); } return weeks; }
function categoryInfo(v) { return CATEGORIES.find((x) => x.value === v) || CATEGORIES[2]; }
function priorityInfo(v) { return PRIORITIES.find((x) => x.value === v) || PRIORITIES[1]; }
function statusInfo(v) { return STATUSES.find((x) => x.value === v) || STATUSES[0]; }
function goalColorInfo(v) { return GOAL_COLORS.find((x) => x.value === v) || GOAL_COLORS[0]; }
function formatDate(v) { const d = dateFromISO(v); return `${d.getDate()} ${MONTHS[d.getMonth()]}`; }
function normTask(x) { const status = x?.status || (x?.failed ? "failed" : x?.done || x?.completed ? "done" : "pending"); return { id: String(x?.id || Date.now() + Math.random()), title: x?.title || x?.name || "İsimsiz iş", category: x?.category || "gunluk", priority: x?.priority || "orta", date: x?.date || x?.dueDate || todayISO(), note: x?.note || "", status }; }
function normGoal(x) { return { id: String(x?.id || Date.now() + Math.random()), title: x?.title || "Yeni Hedef", progress: Math.max(0, Math.min(100, Number(x?.progress || 0))), color: x?.color || "blue", note: x?.note || "" }; }

export default function RoutinePlanner({ routines, setRoutines }) {
  const data = Array.isArray(routines) ? routines : [];
  const tasks = data.filter((x) => x?.recordType !== "goal").map(normTask);
  const goals = data.filter((x) => x?.recordType === "goal").map(normGoal);
  const currentYear = new Date().getFullYear();
  const [year, setYear] = useState(currentYear);
  const [month, setMonth] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [priorityFilter, setPriorityFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [selectedDate, setSelectedDate] = useState(null);
  const [dayNote, setDayNote] = useState("");
  const [quickTitle, setQuickTitle] = useState("");
  const [quickCategory, setQuickCategory] = useState("gunluk");
  const [quickPriority, setQuickPriority] = useState("orta");
  const [taskForm, setTaskForm] = useState({ title: "", category: "egitim", priority: "orta", date: todayISO(), note: "" });
  const [goalForm, setGoalForm] = useState({ title: "", progress: "0", color: "blue", note: "" });
  const [editTaskId, setEditTaskId] = useState(null);
  const [editTask, setEditTask] = useState({ title: "", category: "gunluk", priority: "orta", date: todayISO(), note: "" });
  const [editGoalId, setEditGoalId] = useState(null);
  const [editGoal, setEditGoal] = useState({ title: "", progress: "0", color: "blue", note: "" });
  const [collapsedMonths, setCollapsedMonths] = useState({});
  const [open, setOpen] = useState({ hero: true, goals: true, add: true, filters: true, months: true, calendar: true, dayNote: true, upcoming: true, goalSummary: true });
  const togglePanel = (k) => setOpen((c) => ({ ...c, [k]: !c[k] }));

  const weeks = useMemo(() => buildWeeks(year), [year]);
  const filtered = useMemo(() => tasks.filter((t) => { const d = dateFromISO(t.date); return d.getFullYear() === Number(year) && (month === "all" || d.getMonth() === Number(month)) && (statusFilter === "all" || t.status === statusFilter) && (categoryFilter === "all" || t.category === categoryFilter) && (priorityFilter === "all" || t.priority === priorityFilter) && (!search.trim() || `${t.title} ${t.note}`.toLowerCase().includes(search.toLowerCase())); }), [tasks, year, month, statusFilter, categoryFilter, priorityFilter, search]);
  const byDate = useMemo(() => filtered.reduce((m, t) => { (m[t.date] ||= []).push(t); return m; }, {}), [filtered]);
  const allByDate = useMemo(() => tasks.reduce((m, t) => { (m[t.date] ||= []).push(t); return m; }, {}), [tasks]);
  const stats = useMemo(() => ({ total: filtered.length, done: filtered.filter((t) => t.status === "done").length, failed: filtered.filter((t) => t.status === "failed").length }), [filtered]);
  const goalAverage = goals.length ? Math.round(goals.reduce((s, g) => s + g.progress, 0) / goals.length) : 0;
  const upcoming = tasks.filter((t) => t.status === "pending" && dateFromISO(t.date) >= dateFromISO(todayISO())).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 10);

  const addItem = (payload) => setRoutines?.((cur) => [{ id: String(Date.now()), status: "pending", done: false, completed: false, failed: false, ...payload }, ...(Array.isArray(cur) ? cur : [])]);
  const updateItem = (id, patch) => setRoutines?.((cur) => (Array.isArray(cur) ? cur : []).map((x) => String(x.id) === String(id) ? { ...x, ...patch } : x));
  const deleteItem = (id) => setRoutines?.((cur) => (Array.isArray(cur) ? cur : []).filter((x) => String(x.id) !== String(id)));
  const addTask = () => { const title = taskForm.title.trim(); if (!title) return alert("Rutin / iş adı gir."); addItem({ ...taskForm, title, note: taskForm.note.trim(), date: taskForm.date || selectedDate || todayISO() }); setTaskForm({ title: "", category: taskForm.category, priority: "orta", date: selectedDate || todayISO(), note: "" }); };
  const addGoal = () => { const title = goalForm.title.trim(); if (!title) return alert("Hedef adı gir."); addItem({ recordType: "goal", title, progress: Math.max(0, Math.min(100, Number(goalForm.progress || 0))), color: goalForm.color, note: goalForm.note.trim() }); setGoalForm({ title: "", progress: "0", color: goalForm.color, note: "" }); };
  const addQuick = () => { if (!selectedDate) return alert("Önce takvimden gün seç."); const title = quickTitle.trim(); if (!title) return alert("Başlık gir."); addItem({ title, category: quickCategory, priority: quickPriority, date: selectedDate, note: "" }); setQuickTitle(""); };
  const addNote = () => { if (!selectedDate) return alert("Önce takvimden gün seç."); const note = dayNote.trim(); if (!note) return alert("Not gir."); addItem({ title: `Gün Notu - ${formatDate(selectedDate)}`, category: "not", priority: "orta", date: selectedDate, note }); setDayNote(""); };
  const selectDay = (d) => { if (selectedDate === d) { setSelectedDate(null); setQuickTitle(""); setDayNote(""); setOpen((c) => ({ ...c, dayNote: false })); } else { setSelectedDate(d); setTaskForm((c) => ({ ...c, date: d })); setOpen((c) => ({ ...c, dayNote: true })); } };
  const changeStatus = (id, status) => updateItem(id, { status, done: status === "done", completed: status === "done", failed: status === "failed" });
  const startTaskEdit = (t) => { setEditTaskId(t.id); setEditTask({ title: t.title, category: t.category, priority: t.priority, date: t.date, note: t.note || "" }); };
  const saveTaskEdit = (id) => { const title = editTask.title.trim(); if (!title) return alert("Başlık boş olamaz."); updateItem(id, { ...editTask, title, note: editTask.note.trim() }); setEditTaskId(null); };
  const startGoalEdit = (g) => { setEditGoalId(g.id); setEditGoal({ title: g.title, progress: String(g.progress), color: g.color, note: g.note || "" }); };
  const saveGoalEdit = (id) => { const title = editGoal.title.trim(); if (!title) return alert("Hedef adı boş olamaz."); updateItem(id, { ...editGoal, title, progress: Math.max(0, Math.min(100, Number(editGoal.progress || 0))), note: editGoal.note.trim() }); setEditGoalId(null); };

  return <section style={{ display: "grid", gridTemplateColumns: "minmax(0, 1fr) 360px", gap: 22, alignItems: "start" }}>
    <div>
      <Panel title="🗓️ Rutin Takvimi" open={open.hero} onToggle={() => togglePanel("hero")} gradient="linear-gradient(135deg, rgba(30,64,175,.88), rgba(88,28,135,.82), rgba(15,23,42,.92))"><div style={{ display: "flex", justifyContent: "space-between", gap: 16, flexWrap: "wrap" }}><div><h2 style={{ margin: 0, color: "#fff", fontSize: 34 }}>{year} Planı</h2><p style={{ color: "#dbeafe" }}>Alanlar açılır/kapanır. Hedefler düzenlenebilir. Kartlar daha ferah görünümdedir.</p></div><Field label="Yıl"><Select value={year} onChange={setYear} options={[currentYear - 1, currentYear, currentYear + 1].map((y) => ({ value: y, label: String(y) }))} /></Field></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(130px, 1fr))", gap: 12, marginTop: 18 }}><Stat label="Rutin" value={stats.total} color="#60a5fa" /><Stat label="Tamamlandı" value={stats.done} color="#22c55e" /><Stat label="Tamamlanamadı" value={stats.failed} color="#ef4444" /><Stat label="Hedef Ort." value={`%${goalAverage}`} color="#a78bfa" /></div></Panel>

      <Panel title="🎯 Hedeflerim" open={open.goals} onToggle={() => togglePanel("goals")} gradient="linear-gradient(145deg, rgba(49,46,129,.88), rgba(8,47,73,.82), rgba(15,23,42,.88))"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 12, marginBottom: 14 }}><Field label="Hedef"><input style={inputStyle} value={goalForm.title} onChange={(e) => setGoalForm((c) => ({ ...c, title: e.target.value }))} placeholder="SQL, Saz, İngilizce" /></Field><Field label="İlerleme %"><input style={inputStyle} type="number" min="0" max="100" value={goalForm.progress} onChange={(e) => setGoalForm((c) => ({ ...c, progress: e.target.value }))} /></Field><Field label="Renk"><Select value={goalForm.color} onChange={(v) => setGoalForm((c) => ({ ...c, color: v }))} options={GOAL_COLORS.map((x) => ({ value: x.value, label: x.label }))} /></Field><Field label="Not"><input style={inputStyle} value={goalForm.note} onChange={(e) => setGoalForm((c) => ({ ...c, note: e.target.value }))} placeholder="Opsiyonel" /></Field><button style={primaryButton("linear-gradient(135deg,#c4b5fd,#67e8f9,#fef08a)")} onClick={addGoal}>Hedef Ekle</button></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 12 }}>{goals.length === 0 ? <Empty text="Henüz hedef yok." /> : goals.map((g) => <GoalCard key={g.id} goal={g} editId={editGoalId} edit={editGoal} setEdit={setEditGoal} onEdit={startGoalEdit} onSave={saveGoalEdit} onCancel={() => setEditGoalId(null)} onDelete={deleteItem} />)}</div></Panel>

      <Panel title="➕ Yeni Rutin / İş Ekle" open={open.add} onToggle={() => togglePanel("add")} gradient="linear-gradient(145deg, rgba(6,78,59,.88), rgba(15,23,42,.86))"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12 }}><Field label="Başlık"><input style={inputStyle} value={taskForm.title} onChange={(e) => setTaskForm((c) => ({ ...c, title: e.target.value }))} /></Field><Field label="Kategori"><Select value={taskForm.category} onChange={(v) => setTaskForm((c) => ({ ...c, category: v }))} options={CATEGORIES.map((x) => ({ value: x.value, label: `${x.icon} ${x.label}` }))} /></Field><Field label="Öncelik"><Select value={taskForm.priority} onChange={(v) => setTaskForm((c) => ({ ...c, priority: v }))} options={PRIORITIES.map((x) => ({ value: x.value, label: `${x.icon} ${x.label}` }))} /></Field><Field label="Tarih"><input style={inputStyle} type="date" value={taskForm.date} onChange={(e) => setTaskForm((c) => ({ ...c, date: e.target.value }))} /></Field><Field label="Not"><input style={inputStyle} value={taskForm.note} onChange={(e) => setTaskForm((c) => ({ ...c, note: e.target.value }))} /></Field><button style={primaryButton("linear-gradient(135deg,#fef08a,#34d399,#22d3ee)")} onClick={addTask}>Ekle</button></div></Panel>

      <Panel title="🔎 Filtreler" open={open.filters} onToggle={() => togglePanel("filters")} gradient="linear-gradient(145deg, rgba(120,53,15,.88), rgba(88,28,135,.70), rgba(15,23,42,.86))"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 12 }}><Field label="Ay"><Select value={month} onChange={setMonth} options={[{ value: "all", label: "Tüm Aylar" }, ...MONTHS.map((m, i) => ({ value: String(i), label: m }))]} /></Field><Field label="Durum"><Select value={statusFilter} onChange={setStatusFilter} options={[{ value: "all", label: "Tümü" }, ...STATUSES.map((x) => ({ value: x.value, label: `${x.icon} ${x.label}` }))]} /></Field><Field label="Kategori"><Select value={categoryFilter} onChange={setCategoryFilter} options={[{ value: "all", label: "Tüm Kategoriler" }, ...CATEGORIES.map((x) => ({ value: x.value, label: `${x.icon} ${x.label}` }))]} /></Field><Field label="Öncelik"><Select value={priorityFilter} onChange={setPriorityFilter} options={[{ value: "all", label: "Tüm Öncelikler" }, ...PRIORITIES.map((x) => ({ value: x.value, label: `${x.icon} ${x.label}` }))]} /></Field><Field label="Arama"><input style={inputStyle} value={search} onChange={(e) => setSearch(e.target.value)} /></Field></div></Panel>

      <Panel title="📅 Aylar" open={open.months} onToggle={() => togglePanel("months")} gradient="linear-gradient(145deg, rgba(30,41,59,.90), rgba(49,46,129,.64), rgba(15,23,42,.86))"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 12 }}><MonthCard title="Tüm Yıl" count={filtered.length} active={month === "all"} onClick={() => setMonth("all")} />{MONTHS.map((m, i) => <MonthCard key={m} title={m} count={tasks.filter((t) => dateFromISO(t.date).getFullYear() === Number(year) && dateFromISO(t.date).getMonth() === i).length} active={month === String(i)} collapsed={collapsedMonths[i]} onClick={() => setMonth(String(i))} onToggle={() => setCollapsedMonths((c) => ({ ...c, [i]: !c[i] }))} color={MONTH_GRADIENTS[i]} />)}</div></Panel>

      <Panel title="📌 Haftalık Takvim" open={open.calendar} onToggle={() => togglePanel("calendar")} gradient="linear-gradient(145deg, rgba(8,47,73,.88), rgba(15,23,42,.88))"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(420px, 1fr))", gap: 16 }}>{weeks.filter((w) => (month === "all" || w.monthIndex === Number(month)) && !collapsedMonths[w.monthIndex]).map((w) => { const weekTasks = w.days.flatMap((d) => byDate[localISO(d)] || []); const selectedInWeek = selectedDate && w.days.some((d) => localISO(d) === selectedDate); const visible = selectedInWeek ? byDate[selectedDate] || [] : weekTasks; return <div key={w.id} style={{ ...glass, background: `linear-gradient(145deg, ${MONTH_GRADIENTS[w.monthIndex]}, rgba(15,23,42,.76))`, borderRadius: 24, padding: 16 }}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 12 }}><strong style={{ color: "#fff" }}>{w.monthName}</strong><span style={{ color: "#dbeafe", fontWeight: 900 }}>{w.number}. Hafta</span></div><div style={{ display: "grid", gridTemplateColumns: "repeat(7, minmax(0, 1fr))", gap: 6, marginBottom: 12 }}>{w.days.map((d, i) => { const key = localISO(d); const dayTasks = byDate[key] || []; const selected = key === selectedDate; return <button key={key} onClick={() => selectDay(key)} style={dayStyle(selected, key === todayISO())}><strong>{DAYS[i]}</strong><div>{d.getDate()}</div><div style={{ display: "flex", gap: 3, flexWrap: "wrap", marginTop: 5 }}>{dayTasks.slice(0, 4).map((t) => <span key={t.id} style={{ width: 7, height: 7, borderRadius: 99, background: statusInfo(t.status).color }} />)}</div></button>; })}</div>{selectedInWeek && <QuickEntry selectedDate={selectedDate} quickTitle={quickTitle} setQuickTitle={setQuickTitle} quickCategory={quickCategory} setQuickCategory={setQuickCategory} quickPriority={quickPriority} setQuickPriority={setQuickPriority} addQuick={addQuick} />}<div style={{ display: "flex", flexDirection: "column", gap: 10 }}>{visible.length === 0 ? <Empty text={selectedInWeek ? "Seçili tarihe ait rutin yok." : "Bu haftaya kayıt yok."} /> : visible.map((t) => <TaskCard key={t.id} task={t} editId={editTaskId} edit={editTask} setEdit={setEditTask} onEdit={startTaskEdit} onSave={saveTaskEdit} onCancel={() => setEditTaskId(null)} onStatus={changeStatus} onDelete={deleteItem} />)}</div></div>; })}</div></Panel>

      {selectedDate && <Panel title={`📝 Seçili Gün Notu - ${formatDate(selectedDate)}`} open={open.dayNote} onToggle={() => togglePanel("dayNote")} gradient="linear-gradient(145deg, rgba(131,24,67,.88), rgba(15,23,42,.88))"><div style={{ display: "grid", gridTemplateColumns: "minmax(0, 1fr) 160px", gap: 12 }}><Field label="Güne Not Ekle"><textarea style={{ ...inputStyle, minHeight: 90 }} value={dayNote} onChange={(e) => setDayNote(e.target.value)} /></Field><button style={primaryButton("linear-gradient(135deg,#f9a8d4,#fef08a)")} onClick={addNote}>Kaydet</button></div><div style={{ marginTop: 14, display: "flex", flexDirection: "column", gap: 10 }}>{selectedDateTasks.length === 0 ? <Empty text="Bu güne ait kayıt yok." /> : selectedDateTasks.map((t) => <TaskCard key={t.id} task={t} editId={editTaskId} edit={editTask} setEdit={setEditTask} onEdit={startTaskEdit} onSave={saveTaskEdit} onCancel={() => setEditTaskId(null)} onStatus={changeStatus} onDelete={deleteItem} />)}</div></Panel>}
    </div>
    <aside><Panel title="⏰ Yaklaşan İşler" open={open.upcoming} onToggle={() => togglePanel("upcoming")} gradient="linear-gradient(145deg, rgba(49,46,129,.88), rgba(15,23,42,.88))"><div style={{ display: "flex", flexDirection: "column", gap: 10 }}>{upcoming.length ? upcoming.map((t) => <SmallTask key={t.id} task={t} />) : <Empty text="Yaklaşan iş yok." />}</div></Panel><Panel title="🎯 Hedef Özeti" open={open.goalSummary} onToggle={() => togglePanel("goalSummary")} gradient="linear-gradient(145deg, rgba(88,28,135,.88), rgba(15,23,42,.88))"><Empty text={`Toplam hedef: ${goals.length} • Ortalama ilerleme: %${goalAverage}`} />{goals.slice(0, 5).map((g) => <GoalMini key={g.id} goal={g} />)}</Panel></aside>
  </section>;
}

function Panel({ title, children, open, onToggle, gradient }) { return <div style={{ ...glass, background: gradient, borderRadius: 26, padding: 20, marginBottom: 18 }}><button onClick={onToggle} style={{ width: "100%", border: 0, background: "transparent", color: "#fff", padding: 0, marginBottom: open ? 16 : 0, display: "flex", justifyContent: "space-between", alignItems: "center", cursor: "pointer", textAlign: "left" }}><h3 style={{ margin: 0, fontSize: 20 }}>{title}</h3><span style={{ width: 34, height: 34, borderRadius: 12, display: "grid", placeItems: "center", background: "rgba(255,255,255,.14)", fontWeight: 900 }}>{open ? "−" : "+"}</span></button>{open ? children : null}</div>; }
function Stat({ label, value, color }) { return <div style={{ ...glass, background: `${color}33`, borderRadius: 20, padding: 16 }}><span style={{ color: "#dbeafe", fontSize: 12, fontWeight: 800 }}>{label}</span><strong style={{ display: "block", color: "#fff", fontSize: 24, marginTop: 6 }}>{value}</strong></div>; }
function Empty({ text }) { return <div style={{ padding: 13, borderRadius: 18, background: "rgba(2,6,23,.38)", border: "1px solid rgba(255,255,255,.12)", color: "#cbd5e1", fontSize: 12 }}>{text}</div>; }
function primaryButton(bg) { return { border: 0, borderRadius: 16, padding: "12px 14px", color: "#08111f", fontWeight: 900, cursor: "pointer", background: bg, alignSelf: "end" }; }
function dayStyle(selected, today) { return { minHeight: 52, borderRadius: 14, padding: 6, background: selected ? "rgba(255,255,255,.28)" : today ? "rgba(255,255,255,.18)" : "rgba(2,6,23,.38)", border: selected ? "2px solid rgba(255,255,255,.88)" : "1px solid rgba(255,255,255,.12)", color: "#fff", fontSize: 11, cursor: "pointer", textAlign: "left" }; }
function MonthCard({ title, count, active, collapsed, onClick, onToggle, color = "rgba(59,130,246,.18)" }) { return <div style={{ ...glass, background: `linear-gradient(145deg, ${color}, rgba(15,23,42,.72))`, borderRadius: 20, padding: 12, transform: active ? "translateY(-4px)" : "none" }}><button onClick={onClick} style={{ border: 0, background: "transparent", color: "#fff", textAlign: "left", width: "100%", cursor: "pointer" }}><strong>{title}</strong><span style={{ display: "block", color: "#dbeafe", fontSize: 12, marginTop: 5 }}>{count} kayıt</span></button>{onToggle && <button onClick={onToggle} style={{ ...compactButton, width: "100%", marginTop: 10 }}>{collapsed ? "Ayı Aç" : "Ayı Kapat"}</button>}</div>; }
function QuickEntry({ selectedDate, quickTitle, setQuickTitle, quickCategory, setQuickCategory, quickPriority, setQuickPriority, addQuick }) { return <div style={{ ...glass, background: "rgba(2,6,23,.42)", borderRadius: 18, padding: 12, marginBottom: 12 }}><strong style={{ color: "#fff", display: "block", marginBottom: 10 }}>⚡ {formatDate(selectedDate)} için hızlı giriş</strong><div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) 130px 120px 90px", gap: 8 }}><input style={inputStyle} value={quickTitle} onChange={(e) => setQuickTitle(e.target.value)} placeholder="Bu güne iş / not yaz" /><Select value={quickCategory} onChange={setQuickCategory} options={CATEGORIES.map((x) => ({ value: x.value, label: `${x.icon} ${x.label}` }))} /><Select value={quickPriority} onChange={setQuickPriority} options={PRIORITIES.map((x) => ({ value: x.value, label: `${x.icon} ${x.label}` }))} /><button style={primaryButton("linear-gradient(135deg,#bfdbfe,#67e8f9)")} onClick={addQuick}>Ekle</button></div></div>; }

function GoalCard({ goal, editId, edit, setEdit, onEdit, onSave, onCancel, onDelete }) { const c = goalColorInfo(goal.color); const isEdit = String(editId || "") === String(goal.id); if (isEdit) return <div style={{ ...glass, background: `${c.color}22`, borderColor: `${c.color}66`, borderRadius: 22, padding: 16 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(140px,1fr))", gap: 10 }}><Field label="Hedef"><input style={inputStyle} value={edit.title} onChange={(e) => setEdit((x) => ({ ...x, title: e.target.value }))} /></Field><Field label="İlerleme %"><input style={inputStyle} type="number" min="0" max="100" value={edit.progress} onChange={(e) => setEdit((x) => ({ ...x, progress: e.target.value }))} /></Field><Field label="Renk"><Select value={edit.color} onChange={(v) => setEdit((x) => ({ ...x, color: v }))} options={GOAL_COLORS.map((x) => ({ value: x.value, label: x.label }))} /></Field><Field label="Not"><input style={inputStyle} value={edit.note} onChange={(e) => setEdit((x) => ({ ...x, note: e.target.value }))} /></Field></div><div style={{ display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 12 }}><button style={compactButton} onClick={() => onSave(goal.id)}>Kaydet</button><button style={compactButton} onClick={onCancel}>Vazgeç</button><button style={{ ...compactButton, color: "#fecaca" }} onClick={() => onDelete(goal.id)}>Sil</button></div></div>; return <div style={{ ...glass, background: `${c.color}22`, borderColor: `${c.color}66`, borderRadius: 22, padding: 16 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><div><strong style={{ color: "#fff", fontSize: 18 }}>{goal.title}</strong>{goal.note && <span style={{ display: "block", color: "#cbd5e1", fontSize: 12, marginTop: 5 }}>{goal.note}</span>}</div><strong style={{ color: c.color, fontSize: 22 }}>%{goal.progress}</strong></div><div style={{ height: 14, borderRadius: 99, background: "rgba(2,6,23,.45)", marginTop: 14, overflow: "hidden" }}><div style={{ width: `${goal.progress}%`, height: "100%", background: `linear-gradient(90deg,${c.color},#fff)` }} /></div><div style={{ display: "grid", gridTemplateColumns: "1fr 80px 72px 52px", gap: 8, marginTop: 14, alignItems: "center" }}><input type="range" min="0" max="100" value={goal.progress} onChange={(e) => onSave ? null : null} disabled /><input style={{ ...inputStyle, padding: "8px" }} value={goal.progress} readOnly /><button style={compactButton} onClick={() => onEdit(goal)}>Düzenle</button><button style={{ ...compactButton, color: "#fecaca" }} onClick={() => onDelete(goal.id)}>Sil</button></div></div>; }
function GoalMini({ goal }) { const c = goalColorInfo(goal.color); return <div style={{ padding: 13, borderRadius: 18, background: `${c.color}22`, border: `1px solid ${c.color}66`, marginTop: 10 }}><strong style={{ color: "#fff" }}>{goal.title} • %{goal.progress}</strong><div style={{ height: 8, borderRadius: 99, background: "rgba(2,6,23,.45)", marginTop: 8, overflow: "hidden" }}><div style={{ width: `${goal.progress}%`, height: "100%", background: c.color }} /></div></div>; }

function TaskCard({ task, editId, edit, setEdit, onEdit, onSave, onCancel, onStatus, onDelete }) { const [open, setOpen] = useState(false); const cat = categoryInfo(task.category); const pr = priorityInfo(task.priority); const st = statusInfo(task.status); const isEdit = String(editId || "") === String(task.id); if (isEdit) return <div style={{ ...glass, background: cat.bg, borderColor: `${cat.color}66`, borderRadius: 18, padding: 12 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: 8 }}><Field label="Başlık"><input style={inputStyle} value={edit.title} onChange={(e) => setEdit((x) => ({ ...x, title: e.target.value }))} /></Field><Field label="Kategori"><Select value={edit.category} onChange={(v) => setEdit((x) => ({ ...x, category: v }))} options={CATEGORIES.map((x) => ({ value: x.value, label: `${x.icon} ${x.label}` }))} /></Field><Field label="Öncelik"><Select value={edit.priority} onChange={(v) => setEdit((x) => ({ ...x, priority: v }))} options={PRIORITIES.map((x) => ({ value: x.value, label: `${x.icon} ${x.label}` }))} /></Field><Field label="Tarih"><input style={inputStyle} type="date" value={edit.date} onChange={(e) => setEdit((x) => ({ ...x, date: e.target.value }))} /></Field><Field label="Not"><input style={inputStyle} value={edit.note} onChange={(e) => setEdit((x) => ({ ...x, note: e.target.value }))} /></Field></div><div style={{ display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 12 }}><button style={compactButton} onClick={() => onSave(task.id)}>Kaydet</button><button style={compactButton} onClick={onCancel}>Vazgeç</button><button style={{ ...compactButton, color: "#fecaca" }} onClick={() => onDelete(task.id)}>Sil</button></div></div>;
return <div style={{ ...glass, background: cat.bg, borderColor: `${cat.color}66`, borderRadius: 18, padding: 12, opacity: task.status === "done" ? .8 : task.status === "failed" ? .68 : 1 }}><div style={{ display: "flex", gap: 10, alignItems: "flex-start" }}><div style={{ width: 28, height: 28, borderRadius: 10, display: "grid", placeItems: "center", background: "rgba(255,255,255,.16)", color: st.color }}>{st.icon}</div><button onClick={() => setOpen((v) => !v)} style={{ border: 0, background: "transparent", padding: 0, cursor: "pointer", textAlign: "left", flex: 1 }}><strong style={{ color: "#fff", fontSize: 14, lineHeight: 1.35 }}>{task.title}</strong><span style={{ display: "inline-flex", marginTop: 7, padding: "5px 9px", borderRadius: 99, background: "rgba(255,255,255,.14)", color: "#fff", fontSize: 11, fontWeight: 800 }}>📅 {formatDate(task.date)} • {cat.icon} {cat.label} • {pr.icon} {pr.label}</span></button></div><div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 7, marginTop: 11 }}><select value={task.status || "pending"} onChange={(e) => onStatus(task.id, e.target.value)} style={{ ...compactSelectStyle, width: "100%", borderColor: `${st.color}66` }}>{STATUSES.map((x) => <option key={x.value} value={x.value}>{x.icon} {x.label}</option>)}</select><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 7 }}><button style={compactButton} onClick={() => setOpen((v) => !v)}>{open ? "Kapat" : "Aç"}</button><button style={compactButton} onClick={() => onEdit(task)}>Düzenle</button><button style={{ ...compactButton, color: "#fecaca" }} onClick={() => onDelete(task.id)}>Sil</button></div></div>{open && <div style={{ marginTop: 10, padding: 10, borderRadius: 14, background: "rgba(2,6,23,.28)", border: "1px solid rgba(255,255,255,.12)", color: "#cbd5e1", fontSize: 12 }}>Durum: {st.label} • Tarih: {formatDate(task.date)}<br />Kategori: {cat.label} • Öncelik: {pr.label}{task.note ? <div style={{ color: "#fff", marginTop: 8 }}>{task.note}</div> : <div style={{ color: "#94a3b8", marginTop: 8 }}>Not yok.</div>}</div>}</div>; }
function SmallTask({ task }) { const cat = categoryInfo(task.category); return <div style={{ padding: 13, borderRadius: 18, background: cat.bg, border: `1px solid ${cat.color}66` }}><strong style={{ color: "#fff" }}>{cat.icon} {task.title}</strong><span style={{ display: "block", color: "#dbeafe", fontSize: 12, marginTop: 5 }}>{formatDate(task.date)} • {cat.label}</span></div>; }

